"""empty message

Revision ID: 06a22c066520
Revises: 81f709f98c51
Create Date: 2022-12-17 18:19:26.908292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a22c066520'
down_revision = '81f709f98c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('news_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_type_id'], ['news_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
